#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_dex"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

search_path=$(echo "${XDG_DATA_HOME:-"$HOME/.local/share"}:${XDG_DATA_DIRS:-"/usr/local/share:/usr/share"}" | \
	sed 's/:\|$/\/applications:/g')

IFS=':'
if stest -dqr -n "$cache" $search_path; then
  for location in $search_path; do
    find "$location" -name "*.desktop" ! -exec grep -q '^NoDisplay=true' {} \; \
      -exec sh -c 'printf "%s\t%s\n" "$(grep -m1 '^Name=' "$0" | cut -d '=' -f2)" "$0"' {} \;
  done | sort -u -t "$(printf "\t")" -k1,1 | tee "$cache"
else
	cat "$cache"
fi

unset search_path cachedir cache IFS
exit 0
