#!/bin/sh

apps=$(dmenu_dex)
selected=$(echo "$apps" | cut -d "$(printf "\t")" -f1 | \
  dmenu -i -F -l 20 -z 480 -h 25 -bw 3 -p "Applications")

selected="$(echo "$apps" | grep "^$selected$(printf "\t")")"
[ -n "$selected" ] && echo "$selected" | cut -d "$(printf "\t")" -f2 | \
	xargs basename | xargs setsid -f gtk-launch

unset apps selected
exit 0
