#!/bin/sh

apps=$(dmenu_dex)
selected=$(echo "$apps" | cut -d "$(printf "\t")" -f1 | dmenu "$@")

selected="$(echo "$apps" | grep "^$selected$(printf "\t")")"
[ -n "$selected" ] && launch="$(echo "$selected" | cut -d "$(printf "\t")" -f2)" && \
  setsid -f gtk-launch "$(basename "$launch")"

unset apps selected
exit 0
